import { Roboto } from "next/font/google";
import "./globals.css";
import SideNav from "./components/sideNav";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="bg-white min-h-screen grid grid-rows-6 grid-flow-col">
          <SideNav />
          {children}
        </div>
      </body>
    </html>
  );
}
