import { Roboto } from "next/font/google";
import "./globals.css";
import SideNav from "./components/sideNav";
import TableDetails from "./components/tableDetails";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="bg-white min-h-screen flex">
          <SideNav />
          {children}
          {/* <div className="row-span-1 col-span-7 bg-pink-300">Footer</div>    */}
          <TableDetails />
        </div>
      </body>
    </html>
  );
}
